# -*- coding: utf-8 -*-
"""educação - Otimizador de gestao de tempo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0HIYBUvcdkYYbvATtTRhuFyPSM7OJDi
"""

import numpy as np
import pandas as pd

# ===== Dados extraídos da imagem =====
tarefas = [
    ("Estudar Python", 2, 5),
    ("Exercícios Físicos", 1, 3),
    ("Responder Emails", 1, 2),
    ("Planejar Reunião", 2, 4),
    ("Pesquisa de Mercado", 3, 6),
    ("Ler Artigos", 1, 2),
    ("Codificar Projeto", 4, 7),
    ("Revisar Código", 2, 5),
    ("Criar Apresentação", 3, 6),
    ("Networking", 2, 4),
]

df = pd.DataFrame(tarefas, columns=["nome", "duracao", "valor"])
display(df)

# Limite de horas no dia
LIMITE_TEMPO = 8

# Extrai dados
dur = df["duracao"].values
val = df["valor"].values
N = len(df)

# ===== Programação Dinâmica =====
dp = np.zeros((N + 1, LIMITE_TEMPO + 1), dtype=int)

for i in range(1, N + 1):
    for t in range(1, LIMITE_TEMPO + 1):
        if dur[i - 1] <= t:
            dp[i][t] = max(dp[i - 1][t],
                           dp[i - 1][t - dur[i - 1]] + val[i - 1])
        else:
            dp[i][t] = dp[i - 1][t]

# ===== Recuperar solução =====
t = LIMITE_TEMPO
itens_escolhidos = []

for i in range(N, 0, -1):
    if dp[i][t] != dp[i - 1][t]:
        itens_escolhidos.append(i - 1)
        t -= dur[i - 1]

itens_escolhidos = itens_escolhidos[::-1]

print("===== TAREFAS ESCOLHIDAS PARA O DIA =====")
for idx in itens_escolhidos:
    print(f"- {df.iloc[idx]['nome']} (duração: {df.iloc[idx]['duracao']}h, valor: {df.iloc[idx]['valor']})")

print("\nValor total:", dp[N][LIMITE_TEMPO])
print("Tempo total:", sum(df.iloc[i]["duracao"] for i in itens_escolhidos), "/", LIMITE_TEMPO)

import matplotlib.pyplot as plt

# Dados das tarefas selecionadas
tarefas = ["Estudar Python", "Exercícios Físicos", "Responder Emails", "Planejar Reunião", "Revisar Código"]
duracoes = [2, 1, 1, 2, 2]

plt.figure(figsize=(10, 5))
plt.bar(tarefas, duracoes)
plt.xlabel("Tarefas")
plt.ylabel("Duração (horas)")
plt.title("Duração das Tarefas Selecionadas")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

